name: vrtooldocs_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-forge::python=3.10
  # Declared explicitly through pip due to 7.3.7 not being yet present in conda-forge
  # - conda-forge::sphinx
  - conda-forge::pip
  - pip:
    - sphinx>=7.3.7
  - conda-forge::jupytext
  - conda-forge::nbsphinx
  - conda-forge::myst-parser
  - conda-forge::sphinx-book-theme
  - conda-forge::sphinx-copybutton
  - conda-forge::sphinx_rtd_theme
  