name: "GitHub Pages documentation deploy"
on:
  push:
    branches: [ main ]

permissions:
    contents: write

jobs:
  docs:
    name: Ubuntu docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          channels: conda-forge, defaults
          channel-priority: strict
          environment-file: .config/environment.yml
          activate-environment: vrtooldocs_env

      # - name: Build docs
      #   run: make html

      - name: Upload to GitHub Pages
        if: ${{ github.event_name != 'pull_request'}}
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
          force_orphan: true